server:
  port: 8064

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.prs.services.college
  
spring:
  datasource:
    url: jdbc:h2:file:./etc/college-service-h2-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
#    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
  h2: 
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true