server:
  port: 8062

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.prs.services

spring:
  datasource:
    url: jdbc:h2:file:./etc/department-service-h2-db;DB_CLOSE_ON_EXIT=FALSE
    username: ${username}
    password: ${password}
    schema: classpath:/sql/schema.sql
    data: classpath:/sql/data.sql
#    dataSourceClassName: org.h2.jdbcx.JdbcDataSource
  h2: 
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

info:
  app:
    name: ${spring.application.name}
    version: ${project.version}
    encoding: ${project.build.sourceEncoding}
    environment: ${spring.profiles.active}
    java:
      version: ${java.version}
environment.decription: Prod environment updated
